name: Typos
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Spell check
        uses: crate-ci/typos@a8168dc2984a9e2352f183ffe788f0f23a300389 # v1.49.1
